# Generated by Django 3.0.5 on 2020-06-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0003_linksmodel_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('href', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('href', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ShowsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('href', models.CharField(max_length=300)),
                ('thumbnail_src', models.CharField(default='None', max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='LinksModel',
        ),
    ]
