# Generated by Django 3.0.5 on 2020-06-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0004_auto_20200630_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodesmodel',
            name='season',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
