# Generated by Django 3.0.5 on 2020-06-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0005_episodesmodel_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodesmodel',
            name='ep',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
