# Generated by Django 3.0.5 on 2020-06-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0006_episodesmodel_ep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodesmodel',
            old_name='ep',
            new_name='episode',
        ),
    ]
