# Generated by Django 3.0.7 on 2020-06-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_app', '0007_auto_20200630_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonmodel',
            name='season',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
